remote_theme: PfeifferChPT/pc-cdn-template
name: "ISE Quellennachweise"
title: "PC-CDN"
subtitle: "ISE / Quellennachweise"
description: "PC-CDN ISE / Quellennachweise | Bildquellennachweise | image source evidence" #metadescription
label: P.C. Netzwerk
markdown: kramdown
highlighter: rouge # pygments or rouge or null
exclude: ["node_modules", "gulpfile.js", "package.json"]
permalink: /:year/:month/:day/:title:output_ext
excerpt_separator: <!--more-->
templateserverurl: https://template.pc-cdn.de
themecolor: dlt
themelogo: https://template.pc-cdn.de/assets/img/logo/logo.png
dummyimage: overlay-pattern.png
themeURI: none
themeBGimage: none
GallerieDir: none
hbbhomeurl: none
livereload: true
author: Christian Pfeiffer
since: 2017

# hostcredits: GHP (githubpages), IDN (IONOS DeployNow), OHI (Own Server)
hostcredit: none
FAS: CSS
# FAS (Fontawesome): CSS (css File) JS (javascript) FASkit (Remote von kit.fontawesome.com)

#deactivaterelatedposts: true
# Pagination Settings 
#pagination:
#  enabled: true
#  per_page: 2
#  permalink: '/page/:num/'
#  title: ' - page :num'
#  limit: 0
#  sort_field: 'date'
#  sort_reverse: true

licen-se:
 CC_BY: "<h4>CC BY</h4>Diese Lizenz erlaubt Dritten, ein Werk zu verbreiten, zu remixen, zu verbessern und darauf aufzubauen, auch kommerziell, solange der Urheber des Originals genannt wird."
 CC_BY-SA: "<h4>CC BY SA</h4>Diese Lizenz erlaubt es Dritten, ein Werk zu verbreiten, zu remixen, zu verbessern und darauf aufzubauen, auch kommerziell, solange der Urheber des Originals genannt wird und die auf seinem Werk basierenden neuen Werke unter denselben Bedingungen veröffentlicht werden."
 CC_BY-ND: "<h4>CC BY ND</h4>Diese Lizenz erlaubt Dritten die Weiterverbreitung des Werkes, kommerziell wie nicht-kommerziell, solange dies ohne Veränderungen und vollständig geschieht und der Urheber genannt wird."
 CC_BY-NC: "<h4>CC BY NC</h4>Diese Lizenz erlaubt Dritten die Weiterverbreitung des Werkes, nicht-kommerziell, solange dies ohne Veränderungen und vollständig geschieht und der Urheber genannt wird."
 CC_BY-NC-SA: "<h4>CC BY NC SA</h4>Diese Lizenz erlaubt es Dritten, ein Werk zu verbreiten, zu remixen, zu verbessern und darauf aufzubauen, nicht-kommerziell, solange der Urheber des Originals genannt wird und die auf seinem Werk basierenden neuen Werke unter denselben Bedingungen veröffentlicht werden."
 CC_BY-NC-ND: "<h4>CC BY NC ND</h4>Diese Lizenz erlaubt Dritten die Weiterverbreitung des Werkes, nicht-kommerziell, solange dies ohne Veränderungen und vollständig geschieht und der Urheber genannt wird."
 CC_ZERO: "<h4>CC0 (CC Zero)</h4>Verzicht auf alle urheberrechtlichen und verwandten Schutzrechte. (Bitte beachten Sie hierbei, dass dies nach dem deutschen Urheberrecht ausgeschlossen ist."
