name: "ISE Quellennachweise"
title: "PC-CDN"
subtitle: "ISE / Quellennachweise"
description: "PC-CDN ISE / Quellennachweise | Bildquellennachweise | image source evidence" #metadescription
label: P.C. Netzwerk
markdown: kramdown
highlighter: rouge # pygments or rouge or null
exclude: ["node_modules", "gulpfile.js", "package.json"]
permalink: /:year/:month/:day/:title:output_ext
excerpt_separator: <!--more-->
templateserverurl: https://template.pc-cdn.de
themecolor: blue
themelogo: https://template.pc-cdn.de/assets/img/logo/logo.png
dummyimage: overlay-pattern.png
themeURI: none
themeBGimage: none
GallerieDir: none
hbbhomeurl: none
livereload: true
author: Christian Pfeiffer
#deactivaterelatedposts: true
# Pagination Settings 
#pagination:
#  enabled: true
#  per_page: 2
#  permalink: '/page/:num/'
#  title: ' - page :num'
#  limit: 0
#  sort_field: 'date'
#  sort_reverse: true

licen-se:
 CC_BY: "<h4>CC BY</h4>"
 CC_BY-SA: "TEST!<h4>CC BY SA</h4>"
 CC_BY-ND: "TEST!<h4>CC BY ND</h4>"
 CC_BY-NC: "TEST!<h4>CC BY NC</h4>"
 CC_BY-NC-SA: "TEST!<h4>CC BY NC SA</h4>"
 CC_BY-NC-ND: "TEST!<h4>CC BY NC ND</h4>"
 CC_ZERO: "TEST!<h4>CC0 (CC Zero)</h4>"
